#! /bin/bash

function check_toplevel_directory {
	true
}
toplevel_directory="$(git rev-parse --show-cdup)"

greenc="\033[32m"
endc="\033[0m"

external_dir_name=.git_externals

function change_toplevel_directory {
	if [ -z $toplevel_directory ];
	then
		true
	else
		pushd $toplevel_directory >/dev/null
	fi
}

function foreach_externals {
	callback_func=$1
	find $external_dir_name -type d -name .git | while read gitdir; do
		dir=$(dirname "$gitdir")
		if [ -d $dir ]; then
		pushd $dir > /dev/null
		external_name=${dir#$external_dir_name}
		$callback_func $dir $external_name
		popd > /dev/null
		fi
	done
}

change_toplevel_directory

