#! /bin/bash

filepath=$(readlink -f $0)
dirpath=$(dirname $filepath)
commonspath=$dirpath"/"commons
. $commonspath

check_toplevel_directory

branchname=$1
if [ -z $branchname ];
then
	echo "usage:git-svn-switch-branch branchname"
	exit 1
fi

git checkout $branchname
if [ $? != 0 ];
then
	exit 1
fi

function checkout_branch {
	git checkout $branchname
	if [ $? != 0 ];
	then
		exit 1
	fi
}

foreach_externals checkout_branch

