#!/bin/bash

filepath=$(readlink $0)
dirpath=$(dirname $filepath)
commonspath=$dirpath"/"commons
. $commonspath

check_toplevel_directory

function do_git_svn () {
	svn_name=$1
	git svn $svn_name
	if [ $? != 0 ];
	then
		echo -e "\033[1;31mgit svn $svn_name may not succ,please read above message\033[0m" >&2
		exit 1
	fi
}

function do_update {
	do_git_svn fetch
	do_git_svn rebase
}

foreach_externals do_update

