#!/bin/bash

filepath=$(readlink $0)
dirpath=$(dirname $filepath)
commonspath=$dirpath"/"commons
. $commonspath

check_toplevel_directory

function check_external {
	external_name=$2
	echo -e "$greenc-----------start check $external_name---------"$endc
	git status
	git-svn-check-unpushed
	echo -e $greenc"-------------end check $external_name----------"$endc
	echo ""
}

foreach_externals check_external

