#! /bin/bash

filepath=$(readlink -f $0)
dirpath=$(dirname $filepath)
commonspath=$dirpath"/"commons
. $commonspath

check_toplevel_directory

branchname=$1
force=$2
if [ -z $branchname ];
then
	echo "usage:git-svn-delete-branch branch_name [-D]"
	exit 1
fi

if [ $force"x" != "-D"x ];
then
	force="-d"
fi

git branch $force $branchname
if [ $? != 0 ];
then
	exit 1
fi

function delete_branch {
	git branch $force $branchname
	if [ $? != 0 ];
	then
		exit 1
	fi
}

foreach_externals delete_branch

