#! /bin/bash

filepath=$(readlink -f $0)
dirpath=$(dirname $filepath)
commonspath=$dirpath"/"commons
. $commonspath

git svn rebase
if [ $? != 0 ];
then
	echo -e "\033[1;31mgit svn rebase may not succ,please read above message\033[0m" >&2
	exit 1
fi
git-svn-externals-update

