#!/bin/bash

toplevel_directory="$(git rev-parse --show-cdup)"
[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; exit 1; }

function do_git_svn () {
	svn_name=$1
	git svn $svn_name
	if [ $? != 0 ];
	then
		echo -e "\033[1;31mgit svn $svn_name may not succ,please read above message\033[0m" >&2
	fi
}

find .git_externals -type d -name .git | while read gitdir; do
	dir=$(dirname "$gitdir")
    if [ -d $dir ]; then
	pushd $dir
	echo $dir
	do_git_svn fetch
	do_git_svn rebase
	popd
    fi
done
